K4S1/Models/LyahnitsLabs/Code2Model.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace K4S1.Models.LyahnitsLabs
{
	public class Code2Model
	{
	}
}

K4S1/Models/LyahnitsLabs/Lab2Input.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace K4S1.Models.LyahnitsLabs
{
	public class Lab2Input
	{
		[Display(Name = "Файл с ключом")]
		[Required(ErrorMessage = "Укажите путь к файлу с ключом")]
		public HttpPostedFileBase Key { get; set; }

		[Display(Name = "Файл с сообщением")]
		[Required(ErrorMessage = "Укажите путь к файлу с сообщением")]
		public HttpPostedFileBase File { get; set; }
	}
}

K4S1/Models/LyahnitsLabs/Lab2Model.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace K4S1.Models.LyahnitsLabs
{
	public class Lab2Model
	{
		public List<long> Randoms { get; set; }

		public List<double> Ghistogramm { get; set; }

		public string Key
		{
			get
			{
				string key = "";

				foreach (var r in Randoms)
				{
					key += r.ToString();
					key += " ";
				}

				return key;
			}
		}

		public long[] Intervals { get; set; }

		public double GhistAll
		{
			get
			{
				double sum = Ghistogramm.Sum() / (double)Ghistogramm.Count;

				return Math.Round(sum, 4);
			}
		}
	}
}

K4S1/Models/LyahnitsLabs/LyahLab1Model.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace K4S1.Models.LyahnitsLabs
{
	public class LyahLab1Model
	{
		[Required(ErrorMessage = "Требуется ввести ключ")]
		[Display(Name = "Ключ")]
		public string Key { get; set; }

		[Display(Name = "Файл с сообщением")]
		[Required(ErrorMessage = "Укажите путь к файлу с сообщением")]
		public HttpPostedFileBase File { get; set; }
	}
}

K4S1/Controllers/LyahnitsLabsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

using K4S1.Models.LyahnitsLabs;

using LyahLabs;

namespace K4S1.Controllers
{
    public class LyahnitsLabsController : Controller
    {
        // GET: LyahnitsLab
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Lab1()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Code()
		{
            LyahLab1Model model = new LyahLab1Model();

            return View(model);
		}

        [HttpPost]
        public ActionResult Code(LyahLab1Model model)
        {
            StreamReader reader = new StreamReader(model.File.InputStream);
            string text = reader.ReadToEnd();

            string result = CodeMethods.Lab1Code(model.Key, text);

            var bytes = Encoding.ASCII.GetBytes(result); //Data to be downloaded

            return File(bytes, "text/plain", "coding.txt");
        }

        [HttpGet]
        public ActionResult Decode()
        {
            LyahLab1Model model = new LyahLab1Model();

            return View(model);
        }

        [HttpPost]
        public ActionResult Decode(LyahLab1Model model)
        {
            StreamReader reader = new StreamReader(model.File.InputStream);
            string text = reader.ReadToEnd();

            string result = CodeMethods.Lab1Decode(model.Key, text);

            var bytes = Encoding.ASCII.GetBytes(result); //Data to be downloaded

            return File(bytes, "text/plain", "decoding.txt");
        }

        public ActionResult Lab2()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetRandoms(int n)
		{
            Lab2Model model = new Lab2Model
            {
                Randoms = new List<long>(),
                Ghistogramm = new List<double>()
            };

            FuckingRandom fuckingRandom = new FuckingRandom(24);

            for (int i = 0; i < n; i++)
            {
                model.Randoms.Add(fuckingRandom.Next());
            }

            Ghistogramm ghistogramm = new Ghistogramm(24);
            model.Ghistogramm = ghistogramm.GetGhist(model.Randoms).ToList();
            model.Intervals = ghistogramm.GetIntervarls();

            return View(model);
        }

        public ActionResult DownloadKey(string key)
		{
            var bytes = Encoding.ASCII.GetBytes(key); //Data to be downloaded

            return File(bytes, "text/plain", "random-key.txt");
        }

        [HttpGet]
        public ActionResult GhistoCode()
		{
            Lab2Input model = new Lab2Input();

            return View(model);
        }

        [HttpPost]
        public ActionResult GhistoCode(Lab2Input model)
        {
            StreamReader reader = new StreamReader(model.File.InputStream);
            string text = reader.ReadToEnd();

            StreamReader readerKey = new StreamReader(model.Key.InputStream);
            List<string> key = readerKey.ReadToEnd().Split(' ').ToList();

            string code = CodeMethods.Lab2Code(key, text);
            var bytes = Encoding.UTF8.GetBytes(code);

            return File(bytes, "text/plain", "random-code.txt");
        }

        [HttpGet]
        public ActionResult GhistoDecode()
        {
            Lab2Input model = new Lab2Input();

            return View(model);
        }

        [HttpPost]
        public ActionResult GhistoDecode(Lab2Input model)
        {
            StreamReader reader = new StreamReader(model.File.InputStream);
            string text = reader.ReadToEnd();

            StreamReader readerKey = new StreamReader(model.Key.InputStream);
            List<string> key = readerKey.ReadToEnd().Split(' ').ToList();

            string code = CodeMethods.Lab2Code(key, text);
            var bytes = Encoding.Unicode.GetBytes(code);

            return File(bytes, "text/plain", "random-decode.txt");
        }
    }
}

K4S1/Views/LyahnitsLabs/Code.cshtml
@model K4S1.Models.LyahnitsLabs.LyahLab1Model

@{
    ViewBag.Title = "Code";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Code", "LyahnitsLabs", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Key, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Key, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Key, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.File, new { @class = "form-control", @type = "file" })
            @Html.ValidationMessageFor(model => model.File, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

K4S1/Views/LyahnitsLabs/Decode.cshtml
@model K4S1.Models.LyahnitsLabs.LyahLab1Model

@{
    ViewBag.Title = "Decode";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Decode", "LyahnitsLabs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Key, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Key, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Key, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.File, new { @class = "form-control", @type = "file" })
                @Html.ValidationMessageFor(model => model.File, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

K4S1/Views/LyahnitsLabs/GetRandoms.cshtml
@{
    ViewBag.Title = "GetRandoms";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model K4S1.Models.LyahnitsLabs.Lab2Model

@foreach (var random in Model.Randoms)
{
    <span>@random </span>
}

<table class="table">
    <tbody>
        <tr>
            <td>
                0 - @Model.Intervals[0]
            </td>
            <td>
                @Model.Ghistogramm[0]
            </td>

        </tr>
        @for (int i = 1; i < Model.Intervals.Length; i++)
        {
            <tr>
                <td>
                    @Model.Intervals[i - 1]<span> - </span>@Model.Intervals[i]
                </td>
                <td>
                    @Model.Ghistogramm[i]
                </td>
            </tr>
        }
    </tbody>
</table>
<p>
    @Model.GhistAll
</p>

@Html.ActionLink("Скачать ключ", "DownloadKey", "LyahnitsLabs", new { key = Model.Key }, new { @class = "btn btn-primary" })
@Html.ActionLink("Зашифровать", "GhistoCode", "LyahnitsLabs", new { @class = "btn btn-primary" })

K4S1/Views/LyahnitsLabs/GhistoCode.cshtml
@model K4S1.Models.LyahnitsLabs.Lab2Input

@{
    ViewBag.Title = "GhistoCode";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("GhistoCode", "LyahnitsLabs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.Key, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Key, new { @class = "form-control", @type = "file" })
            @Html.ValidationMessageFor(model => model.Key, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.File, new { @class = "form-control", @type = "file" })
            @Html.ValidationMessageFor(model => model.File, "", new { @class = "text-danger" })
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Зашифровать</button>
}

<div>
    @Html.ActionLink("Расшифровать", "GhistoDecode", "LyahnitsLabs", new { @class = "btn btn-primary" })
</div>

K4S1/Views/LyahnitsLabs/GhistoDecode.cshtml
@model K4S1.Models.LyahnitsLabs.Lab2Input

@{
    ViewBag.Title = "GhistoDeode";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("GhistoDecode", "LyahnitsLabs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.Key, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Key, new { @class = "form-control", @type = "file" })
            @Html.ValidationMessageFor(model => model.Key, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.File, new { @class = "form-control", @type = "file" })
            @Html.ValidationMessageFor(model => model.File, "", new { @class = "text-danger" })
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Расшифровать</button>
}

K4S1/Views/LyahnitsLabs/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row" style="margin: 50px 0">
    <div class="col-md-4">
        @Html.ActionLink("Лаб №1", "Lab1", "LyahnitsLabs", new { @class = "btn btn-primary" })
    </div>
</div>

K4S1/Views/LyahnitsLabs/Lab1.cshtml
@{
    ViewBag.Title = "Lab1";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row" style="margin: 50px 0">
    <div class="col-md-4">
        @Html.ActionLink("Кодирование", "Code", "LyahnitsLabs", new { @class = "btn btn-primary" })
    </div>
    <div class="col-md-4">
        @Html.ActionLink("Декодирование", "Decode", "LyahnitsLabs", new { @class = "btn btn-primary" })
    </div>
</div>

K4S1/Views/LyahnitsLabs/Lab2.cshtml
@{
    ViewBag.Title = "Lab2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("GetRandoms", "LyahnitsLabs", FormMethod.Post))
{
    <div class="form-horizontal">
        <input type="text" name="n" id="n" />
        <button class="btn btn-primary" type="submit">Просмотр</button>
    </div>
}