K4S1/Models/KobakLabs/FinalStatisticModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace K4S1.Models.KobakLabs
{
	public class FinalStatisticModel
	{
		public int[,] Matrix { get; set; }

		public List<StatisticElementModel> StatisticElements { get; set; }

		public FinalStatisticModel()
		{
			StatisticElements = new List<StatisticElementModel>();
		}
	}
}

K4S1/Models/KobakLabs/L1ResultModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using KobLabs.Classes;

namespace K4S1.Models.KobakLabs
{
	public class L1ResultModel
	{
		public int[] Tasks { get; set; }

		public int[,] Schedule { get; set; }

		public int[] Results { get; set; }

		public int [] ResultStatistics
		{
			get; set;
		}

		public int [] IndexesStatistics
		{
			get; set;
		}

		public float ResultAverage
		{
			get; set;
		}

		public float IndexAverage
		{
			get; set;
		}

		public int[] TasksAsc { get; set; }

		public int[,] ScheduleAsc { get; set; }

		public int[] ResultsAsc { get; set; }

		public int[] ResultStatisticsAsc
		{
			get; set;
		}

		public int[] IndexesStatisticsAsc
		{
			get; set;
		}

		public float ResultAverageAsc
		{
			get; set;
		}

		public float IndexAverageAsc
		{
			get; set;
		}

		public int[] TasksDesc { get; set; }

		public int[,] ScheduleDesc { get; set; }

		public int[] ResultsDesc { get; set; }

		public int[] ResultStatisticsDesc
		{
			get; set;
		}

		public int[] IndexesStatisticsDesc
		{
			get; set;
		}

		public float ResultAverageDesc
		{
			get; set;
		}

		public float IndexAverageDesc
		{
			get; set;
		}

		public List<MethodModel> Methods { get; set; }
		public L1ResultModel()
		{
		}

		public static explicit operator L1ResultModel(L1Result result)
		{
			if (result == null) return null;
			else return new L1ResultModel
			{
				Tasks = result.Tasks,
				Schedule = result.Schedule,
				Results = result.Results,
				ResultStatistics = result.ResultStatistics,
				IndexesStatistics = result.IndexesStatistics,
				ResultAverage = result.ResultAverage,
				IndexAverage = result.IndexAverage,
				TasksAsc = result.TasksAsc,
				ScheduleAsc = result.ScheduleAsc,
				ResultsAsc = result.ResultsAsc,
				ResultStatisticsAsc = result.ResultStatisticsAsc,
				IndexesStatisticsAsc = result.IndexesStatisticsAsc,
				ResultAverageAsc = result.ResultAverageAsc,
				IndexAverageAsc = result.IndexAverageAsc,
				TasksDesc = result.TasksDesc,
				ScheduleDesc = result.ScheduleDesc,
				ResultsDesc = result.ResultsDesc,
				ResultStatisticsDesc = result.ResultStatisticsDesc,
				IndexesStatisticsDesc = result.IndexesStatisticsDesc,
				ResultAverageDesc = result.ResultAverageDesc,
				IndexAverageDesc = result.IndexAverageDesc,
				Methods = result.Methods.Select(c => (MethodModel)c).ToList(),
			};
		}
	}
}

K4S1/Models/KobakLabs/L1StatisticModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using KobLabs.Classes;

namespace K4S1.Models.KobakLabs
{
	public class L1StatisticModel
	{
		public List<L1ResultModel> Results { get; set; }
		
		public float Staticstics { get; set; }

		public float StaticsticsAsc { get; set; }

		public float StaticsticsDesc { get; set; }

		public float[] Methods { get; set; }

	}
}

K4S1/Models/KobakLabs/L3Element.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using KobLabs.Classes;

namespace K4S1.Models.KobakLabs
{
	public class L3Element
	{
		public int[] Tasks { get; set; }

		public int[,] StartCritical { get; set; }

		public int[,] StartRandom { get; set; }

		public int[,] CriticalSchedule { get; set; }

		public int[,] RandomSchedule { get; set; }

		public int[] CriticalLoad { get; set; }

		public int[] RandomLoad { get; set; }

		public List<MethodModel> MethodStatistics { get; set; }

		public static explicit operator L3Element(L3Result l3)
		{
			if (l3 == null)
			{
				return null;
			}
			else
			{
				L3Element result = new L3Element
				{
					Tasks = l3.Tasks,
					StartCritical = l3.StartCritical,
					StartRandom = l3.StartRandom,
					CriticalSchedule = l3.CriticalSchedule,
					RandomSchedule = l3.RandomSchedule,
					CriticalLoad = l3.CriticalLoad,
					RandomLoad = l3.RandomLoad
				};
				result.MethodStatistics = new List<MethodModel>();
				foreach (var c in l3.MethodStatistics)
				{
					result.MethodStatistics.Add(new MethodModel(c.MethodName, c.MaxLoad));
				}

				return result;
			}
		}
	}
}

K4S1/Models/KobakLabs/L3ResultModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace K4S1.Models.KobakLabs
{
	public class L3ResultModel
	{
		public List<L3Element> Elements { get; set; }

		public List<TopMethod> Top { get; set; }
	}
}

K4S1/Models/KobakLabs/L4Element.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace K4S1.Models.KobakLabs
{
	public class L4Element
	{
		public string Barier { get; set; }

		public List<int[]> Result { get; set; }

		public L4Element()
		{
			Result = new List<int[]>();
		}
	}
}

K4S1/Models/KobakLabs/L4Model.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace K4S1.Models.KobakLabs
{
	public class L4Model
	{
		public List<L4Result> Results { get; set; }

		public List<TopMethod> Tops { get; set; }

		public L4Model()
		{
			Results = new List<L4Result>();
			Tops = new List<TopMethod>();
		}
	}
}

K4S1/Models/KobakLabs/L4Result.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace K4S1.Models.KobakLabs
{
	public class L4Result
	{
		public int[,] Matrix { get; set; }

		public List<L4Element> Methods { get; set; }

		public L4Result()
		{
			Methods = new List<L4Element>();
		}
	}
}

K4S1/Models/KobakLabs/Lab1Input.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace K4S1.Models.KobakLabs
{
	public class Lab1Input
	{
		 [Display(Name = "Число процессоров")]
		 [Required(ErrorMessage = "Поле должно быть заполнено")]
		 public int N { get; set; }
		[Display(Name = "Число заданий")]
		[Required(ErrorMessage = "Поле должно быть заполнено")]
		public int M { get; set; }

		[Display(Name = "Число массивов")]
		[Required(ErrorMessage = "Поле должно быть заполнено")]
		public int Q { get; set; }

		[Display(Name = "Минимальная граница")]
		[Required(ErrorMessage = "Поле должно быть заполнено")]
		public int Min { get; set; }

		[Display(Name = "Максимальная граница")]
		[Required(ErrorMessage = "Поле должно быть заполнено")]
		public int Max { get; set; }
	}
}

K4S1/Models/KobakLabs/MethodEnum.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace K4S1.Models.KobakLabs
{
	public enum MethodEnum
	{
		[Description("Случайный")]
		RandomMethod = 1,

		[Description("По возрастанию")]
		Ascending = 2,

		[Description("По убыванию")]
		Descending = 3,

		[Description("Критический путь")]
		Critical = 4
	}
}

K4S1/Models/KobakLabs/ResultModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace K4S1.Models.KobakLabs
{
	public class ResultModel
	{
		public List<FinalStatisticModel> FinalStatistic { get; set; }

		public List<TopMethod> TopMethod { get; set; }

		public ResultModel()
		{
			FinalStatistic = new List<FinalStatisticModel>();
			TopMethod = new List<TopMethod>();
		}
	}
}

K4S1/Models/KobakLabs/ScheduleResultModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace K4S1.Models.KobakLabs
{
	public class ScheduleResultModel
	{
		public int[,] Schedule { get; set; }

		public int[] Loads { get; set; }

		public string MethodName { get; set; }
	}
}

K4S1/Controllers/KobakLabsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Razor.Parser;

using K4S1.Models.KobakLabs;

using KobLabs;
using KobLabs.Classes;

namespace Controllers
{
    public class KobakLabsController : Controller
    {
        // GET: KobakLabs
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Lab1()
        {
            Lab1Input model = new Lab1Input();
            return View(model);
        }

        [HttpPost]
        public ActionResult Lab1(Lab1Input model)
        {
            if (ModelState.IsValid)
            {
                L1StatisticModel statisticModel = new L1StatisticModel();
                statisticModel.Results = new List<L1ResultModel>();

                var task = new int[model.M];
                Random random = new Random();

                for (int i = 0; i < model.Q; i++)
                {
                    statisticModel.Results.Add((L1ResultModel)Methods.CriticalMethodPath(model.M, model.N, model.Min, model.Max));

                    Thread.Sleep(500);
                }


                foreach (var c in statisticModel.Results)
                {
                    statisticModel.Staticstics += c.Results.Max();
                    statisticModel.StaticsticsDesc += c.ResultsDesc.Max();
                    statisticModel.StaticsticsAsc += c.ResultStatisticsAsc.Max();
                }

                statisticModel.Staticstics = statisticModel.Staticstics / model.Q;
                statisticModel.StaticsticsAsc = statisticModel.StaticsticsAsc / model.Q;
                statisticModel.StaticsticsDesc = statisticModel.StaticsticsDesc / model.Q;

                statisticModel.Methods = new float[3];

                statisticModel.Methods[0] = (float)statisticModel.Results.Sum
                    (
                    c => c.Methods.IndexOf(c.Methods.FirstOrDefault(n => n.MethodName == MethodEnum.RandomMethod)) + 1
                    ) / (float)statisticModel.Results.Count();

                statisticModel.Methods[1] = (float)statisticModel.Results.Sum
                    (
                    c => c.Methods.IndexOf(c.Methods.FirstOrDefault(n => n.MethodName == MethodEnum.Ascending)) + 1
                    ) / (float)statisticModel.Results.Count();

                statisticModel.Methods[2] = (float)statisticModel.Results.Sum
                    (
                    c => c.Methods.IndexOf(c.Methods.FirstOrDefault(n => n.MethodName == MethodEnum.Descending)) + 1
                    ) / (float)statisticModel.Results.Count();

                return View("~/Views/KobakLabs/Lab1Result.cshtml", statisticModel);
            }
            else return View(model);

        }

        public ActionResult Lab2()
        {
            Lab1Input model = new Lab1Input();
            return View(model);
        }

        [HttpPost]
        public ActionResult Lab2(Lab1Input model)
        {
            ResultModel result = new ResultModel();

            for (int i = 0; i < model.Q; i++)
            {
                FinalStatisticModel finalStatistic = new FinalStatisticModel();
                StatisticElementModel element1 = new StatisticElementModel();
                StatisticElementModel element2 = new StatisticElementModel();
                StatisticElementModel element3 = new StatisticElementModel();
                finalStatistic.Matrix = new int[model.M, model.N];

                Random random = new Random();

                for (int m = 0; m < model.M; m++)
                {
                    for (int n = 0; n < model.N; n++)
                    {
                        finalStatistic.Matrix[m, n] = random.Next(model.Min, model.Max);
                    }
                }

                var result1 = Methods.Zverev(finalStatistic.Matrix);
                var result2 = Methods.MinElements(finalStatistic.Matrix);
                var result3 = Methods.Barier(finalStatistic.Matrix);

                element1.Result.Schedule = result1.Result.Schedule;
                element1.Result.MethodName = result1.MethodName;
                element1.Result.Loads = result1.Result.Loads;

                element2.Result.Schedule = result2.Result.Schedule;
                element2.Result.MethodName = result2.MethodName;
                element2.Result.Loads = result2.Result.Loads;

                element3.Result.Schedule = result3.Result.Schedule;
                element3.Result.MethodName = result3.MethodName;
                element3.Result.Loads = result3.Result.Loads;

                finalStatistic.StatisticElements = finalStatistic.StatisticElements.OrderBy(c => c.Result.Loads.Max()).ToList();

                result.FinalStatistic.Add(new FinalStatisticModel
                {
                    Matrix = finalStatistic.Matrix,
                    StatisticElements = new List<StatisticElementModel>
                    {
                        element1, element2, element3
                    }
                });

                Thread.Sleep(500);
            }


            foreach (var e in result.FinalStatistic)
            {
                e.StatisticElements = e.StatisticElements.OrderBy(c => c.Result.Loads.Max()).ToList();
            }


            TopMethod topMethod1 = new TopMethod();
            TopMethod topMethod2 = new TopMethod();
            TopMethod topMethod3 = new TopMethod();

            topMethod1.Method = "Алгоритм Плотникова-Зверева";

            foreach (var e in result.FinalStatistic)
            {
                topMethod1.Method = "Алгоритм Плотникова-Зверева";
                topMethod1.Index += (float)e.StatisticElements.IndexOf(e.StatisticElements.FirstOrDefault(c => c.Result.MethodName == "Алгоритм Плотникова-Зверева")) + 1;

                topMethod2.Method = "Минимальных элементов";
                topMethod2.Index += (float)e.StatisticElements.IndexOf(e.StatisticElements.FirstOrDefault(c => c.Result.MethodName == "Минимальных элементов")) + 1;

                topMethod3.Method = "Поиск с барьером";
                topMethod3.Index += (float)e.StatisticElements.IndexOf(e.StatisticElements.FirstOrDefault(c => c.Result.MethodName == "Поиск с барьером")) + 1;

            }

            topMethod1.Index /= model.Q;

            topMethod2.Index /= model.Q;

            topMethod3.Index /= model.Q;


            result.TopMethod.Add(topMethod1);
            result.TopMethod.Add(topMethod2);
            result.TopMethod.Add(topMethod3);

            return View("~/Views/KobakLabs/Lab2Result.cshtml", result);
        }

        public ActionResult Lab3()
        {
            Lab1Input model = new Lab1Input();
            return View(model);
        }

        [HttpPost]
        public ActionResult Lab3(Lab1Input model)
        {
            L3ResultModel result = new L3ResultModel();
            result.Elements = new List<L3Element>();
            result.Top = new List<TopMethod>();

            for (int i = 0; i < model.Q; i++)
            {
                result.Elements.Add((L3Element)Methods.Kron(model.M, model.N, model.Min, model.Max));

                Thread.Sleep(500);
            }

            result.Top.Add(new TopMethod
            {
                Index = 0,
                Method = "Критический путь"
            });
            result.Top.Add(new TopMethod
            {
                Index = 0,
                Method = "Случайный"
            });

            foreach (var e in result.Elements)
            {
                result.Top[0].Index += (float)e.MethodStatistics.IndexOf(e.MethodStatistics.FirstOrDefault(c => c.MethodName == MethodEnum.Critical)) + 1;
                result.Top[1].Index += (float)e.MethodStatistics.IndexOf(e.MethodStatistics.FirstOrDefault(c => c.MethodName == MethodEnum.RandomMethod)) + 1;
            }

            result.Top[0].Index /= (float)model.Q;
            result.Top[1].Index /= (float)model.Q;

            return View("~/Views/KobakLabs/Lab3Result.cshtml", result);
        }

        public ActionResult Lab4()
        {
            Lab1Input model = new Lab1Input();
            return View(model);
        }

        [HttpPost]
        public ActionResult Lab4(Lab1Input model)
        {
            L4Model result = new L4Model();

            for (int q = 0; q < model.Q; q++)
            {
                int[,] matrix = new int[model.M, model.N];

                Random random = new Random();
                for (int i = 0; i < model.M; i++)
				{
                    for (int j = 0; j < model.N; j++)
					{
                        matrix[i, j] = random.Next(model.Min, model.Max);
					}
				}

                L4Result step = new L4Result();

                step.Matrix= new int[model.M, model.N];

                for (int i = 0; i < model.M; i++)
                {
                    for (int j = 0; j < model.N; j++)
                    {
                        step.Matrix[i, j] = matrix[i, j];
                    }
                }

                int barier1 = 0;
                int barier2 = 0;

                L4Element element1 = new L4Element();
                element1.Barier = "Поиск с барьером по среднему элементов";

                barier1 = Methods.Barier1(matrix);
                var result1 = Methods.BarierMethod(step.Matrix, barier1);

    //            foreach (var e in result1)
    //            {
    //                int[] step2 = new int[e.];

    //                for (int i = 0; i < e.Length; i++)
				//	{
    //                    step2[i] = e[i];
				//	}

    //                element1.Result.Add(step2);
				//}

    //            L4Element element2 = new L4Element();
    //            element2.Barier = "Поиск с барьером по минимальным элементам";

    //            barier2 = Methods.Barier2(matrix);

K4S1/Views/KobakLabs/Index.cshtml
@{
    ViewBag.Title = "Теория принятия решений";
}


<div class="row" style="margin: 50px 0">
    <div class="col-md-4">
        @Html.ActionLink("Лаб №1", "Lab1", "KobakLabs", new { @class = "btn btn-primary" })
    </div>
    <div class="col-md-4">
        @Html.ActionLink("Лаб №2", "Lab2", "KobakLabs", new { @class = "btn btn-primary" })
    </div>
    <div class="col-md-4">
        @Html.ActionLink("Лаб №3", "Lab3", "KobakLabs", new { @class = "btn btn-primary" })
    </div>
</div>

K4S1/Views/KobakLabs/Lab1.cshtml
@model K4S1.Models.KobakLabs.Lab1Input

@{
    ViewBag.Title = "Lab1";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lab1</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Lab1Input</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.N, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.N, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.N, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.M, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.M, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.M, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Q, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Q, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Q, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Min, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Min, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Min, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Max, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Max, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Max, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Подтвердить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

K4S1/Views/KobakLabs/Lab2.cshtml
@model K4S1.Models.KobakLabs.Lab1Input

@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.N, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.N@*, new { htmlAttributes = new { @class = "form-control" } }*@)
                @Html.ValidationMessageFor(model => model.N, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.M, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.M@*, new { htmlAttributes = new { @class = "form-control" } }*@)
                @Html.ValidationMessageFor(model => model.M, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Q, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Q@*, new { htmlAttributes = new { @class = "form-control" } }*@)
                @Html.ValidationMessageFor(model => model.Q, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Min, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Min@*, new { htmlAttributes = new { @class = "form-control" } }*@)
                @Html.ValidationMessageFor(model => model.Min, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Max, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Max@*, new { htmlAttributes = new { @class = "form-control" } }*@)
                @Html.ValidationMessageFor(model => model.Max, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Подтвердить" @*class="btn btn-default"*@ />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

K4S1/Views/KobakLabs/Lab2Result.cshtml
@{
    ViewBag.Title = "Lab2Result";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model K4S1.Models.KobakLabs.ResultModel

@foreach (var element in Model.FinalStatistic)
{
    <p></p>
    <h4>
        Массив №@(Model.FinalStatistic.IndexOf(element) + 1)
    </h4>
    <p></p>
    <table @*class="table"*@ cellspacing="2" border="1" cellpadding="5" width="600"  style="text-align:center;vertical-align:middle">
        <tbody>
            @for (int i = 0; i < element.Matrix.GetLength(0); i++)
            {
                <tr>
                    @for (int j = 0; j < element.Matrix.GetLength(1); j++)
                    {
                        <td>
                            @element.Matrix[i, j]
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>

    <p></p>

    foreach (var e in element.StatisticElements)
    {
        <p>
            @e.Result.MethodName
        </p>

        <table @*class="table"*@ cellspacing="2" border="1" cellpadding="5" width="600"  style="text-align:center;vertical-align:middle">
            <tbody>
                @for (int i = 0; i < e.Result.Schedule.GetLength(0); i++)
                {
                    <tr>
                        @for (int j = 0; j < e.Result.Schedule.GetLength(1); j++)
                        {
                            <td>
                                @e.Result.Schedule[i, j]
                            </td>
                        }
                    </tr>
                }
                <tr>
                    @for (int i = 0; i < e.Result.Loads.Length; i++)
                    {
                        <td>
                            @e.Result.Loads[i]
                        </td>
                    }
                </tr>
            </tbody>
        </table>
    }
    <p></p>
    <table @*class="table"*@ cellspacing="2" border="1" cellpadding="5" width="600" style="text-align:center;vertical-align:middle">
        <tbody>
            @foreach (var c in element.StatisticElements)
            {
                <tr>
                    <td>
                        @(element.StatisticElements.IndexOf(c) + 1)
                    </td>
                    <td>
                        @c.Result.MethodName
                    </td>
                    <td>
                        @c.Result.Loads.Max()
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
<p></p>
<table @*class="table"*@ cellspacing="2" border="1" cellpadding="5" width="600" style="text-align:center;vertical-align:middle">
    <tbody>
        @foreach (var c in Model.TopMethod)
        {
            <tr>
                <td>
                    @c.Method
                </td>
                <td>
                    @c.Index
                </td>
            </tr>
        }
    </tbody>
</table>

K4S1/Views/KobakLabs/Lab4Result.cshtml
@{
    ViewBag.Title = "Lab4Result";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model K4S1.Models.KobakLabs.L4Model

@foreach (var element in Model.Results)
{
    <p>
        <h3>
            Матрица
        </h3>
    </p>
    <table class="table">
        <tbody>
            @for (int i = 0; i < element.Matrix.GetLength(0); i++)
            {
                <tr>
                    @for (int j = 0; j < element.Matrix.GetLength(1); j++)
                    {
                        <td>
                            @element.Matrix[i, j]
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>

    foreach (var result in element.Methods)
    {
        <p>
            <h4>
                @result.Barier
            </h4>
        </p>

        <table class="table">
            <tbody>
                    <tr>
                        @for (int i = 0; i < result.Result[0].Length; i++)
                        {
                        <td>
                            @result.Result[0][i]
                        </td>
                        }
                    </tr>
            </tbody>
        </table>
    }
}

<p>
    <h3>
        Итог
    </h3>
</p>